import "./globals.css";
import { IBM_Plex_Mono } from "next/font/google";

const IBM = IBM_Plex_Mono({ weight: "500", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={IBM.className}>{children}</body>
    </html>
  );
}
